referenceFile:
  class: File
  format: edam:format_2206 # Sequence feature table format (text)
  path: ../../Data/Halichoeres_trimaculatus/braker_correctID_v3.gtf

seedFile:
  class: File
  format: edam:format_3671 # text
  path: ../../Data/Halichoeres_trimaculatus/BSgenome.Htrimaculatus.Htriv1.1-seed_2.txt

threads: 16
inputFilesType: "bamPairedEnd"
organismName: "Halichoeres trimaculatus"

metadata:
  class: File
  format: edam:format_3671 # text
  path: ../../Data/Halichoeres_trimaculatus/sample_metadata.csv

genome_seqs_dir:
  class: Directory
  path: ../../out/seqs_by_scaffold

annotation_region_upstream: 1000
annotation_region_downstream: 0
annotation_type: "genes"

# bamファイル配列の指定方法
bam_files:
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.F1_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.F1.Mix_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.F2_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.F3_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.F4_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.M1_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.M1.Mix_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.M2_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.M3_R1_trim.fq_Aligned.sortedByCoord.out.bam
  - class: File
    format: edam:format_2572 # bam file
    path: ../../out/MK.M4_R1_trim.fq_Aligned.sortedByCoord.out.bam
