THREADS: 16

GENOME_FILE:
  class: File
  format: edam:format_3989
  location: ../../Data/Halichoeres_trimaculatus/Halichoeres_trimaculatus-hifiasm-3ddna-v1.1.edit.fna.gz

seqkit_output_dir_name: seqs_by_scaffold

fastq1_files:
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F1/MK.F1_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F1.Mix/MK.F1.Mix_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F2/MK.F2_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F3/MK.F3_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F4/MK.F4_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M1/MK.M1_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M1.Mix/MK.M1.Mix_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M2/MK.M2_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M3/MK.M3_R1.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M4/MK.M4_R1.fastq.gz

fastq2_files:
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F1/MK.F1_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F1.Mix/MK.F1.Mix_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F2/MK.F2_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F3/MK.F3_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.F4/MK.F4_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M1/MK.M1_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M1.Mix/MK.M1.Mix_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M2/MK.M2_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M3/MK.M3_R2.fastq.gz
  - class: File
    format: edam:format_1930
    location: ../../Data/Halichoeres_trimaculatus/CAGE/All_data/Fastq/MK.M4/MK.M4_R2.fastq.gz
    
fastp_compression_level: 9
star_index_dir_name: star_genome_idx
reference_genome_annotation:
  class: File
  format: edam:format_2306
  location: ../../Data/Halichoeres_trimaculatus/braker_correctID_v3.gtf