star_index_dir: 
  class: Directory
  location: /Volumes/externalSSD4M3Max/test_dir_4_update-gtf_cwl/out/star_genome_idx
star_threads: 16



cage_seq_reads_1:
  - class: File
    format: edam:format_1930
    location: ../out/MK.F1_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F1.Mix_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F2_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F3_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F4_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M1_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M1.Mix_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M2_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M3_R1_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M4_R1_trim.fq.gz

cage_seq_reads_2:
  - class: File
    format: edam:format_1930
    location: ../out/MK.F1_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F1.Mix_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F2_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F3_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.F4_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M1_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M1.Mix_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M2_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M3_R2_trim.fq.gz
  - class: File
    format: edam:format_1930
    location: ../out/MK.M4_R2_trim.fq.gz





